version: '3'

services:
  nginx:
    image: nginx:alpine
    hostname: 'nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - "8082:80"
    depends_on: 
      - api
    restart: always
  
  api:
    image: loadbalancerapi
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;User ID=postgres;Password=123456;Port=5432; Database=LoadBalancerDB; Integrated Security=true; Pooling=true; MultiSubnetFailover=False;
      - Redis_HOSTNAME=redis
    ports:
      - '5000'
    depends_on:
      - redis
    
  redis:
     image: "redis:alpine"
     environment:
      - REDIS_REPLICATION_MODE=master
     ports:
      - '6379:6379'
      
  redis_commander:
    depends_on:
      - redis
    image: rediscommander/redis-commander
    restart: always
    environment:
    - REDIS_HOST=redis
    ports:
    - "8085:8081"